import { ProductPageConfig } from '@/types/pdp-template.types';

export const DEFAULT_PURCHASE_ELEMENTS_ORDER: ProductPageConfig['purchasePanel']['elementsOrder'] = [
  'badges',
  'brand',
  'title',
  'rating',
  'price',
  'discount',
  'colorSwatches',
  'sizeSelector',
  'sizeGuide',
  'stockUrgency',
  'quantity',
  'addToCart',
  'buyNow',
  'wishlist',
  'share',
  'shipping',
  'returns',
  'sku',
];

export const PDP_PRESET_TEMPLATES: Record<string, { name: string; description: string; config: ProductPageConfig }> = {
  default_fashion: {
    name: 'Default Fashion Lookbook (Preset)',
    description: 'Balanced 55/45 split layout with 4:5 portrait ratio, left thumbnails, color/size chips, delivery estimator, and tabbed details.',
    config: {
      id: 'default_fashion',
      name: 'Default Fashion Lookbook',
      isDefault: true,
      gallery: {
        layout: 'left-thumbs',
        aspectRatio: '4:5',
        zoomMode: 'hover',
        thumbnailsPosition: 'left',
        enableVideo: true,
        enable360: false,
        galleryWidthPercent: 55,
        gap: 'medium',
        mobileCarousel: true,
        showImageBadge: true,
      },
      purchasePanel: {
        elementsOrder: [...DEFAULT_PURCHASE_ELEMENTS_ORDER],
        showBrand: true,
        showTitle: true,
        showRating: true,
        showReviewCount: true,
        showPrice: true,
        showComparePrice: true,
        showDiscount: true,
        discountFormat: 'percentage',
        showBadges: true,
        showSKU: true,
        colorDisplayType: 'swatches',
        sizeDisplayType: 'buttons',
        showStockStatus: true,
        showLowStockWarning: true,
        lowStockThreshold: 5,
        lowStockMessage: 'Only {{quantity}} left in stock — order soon',
        outOfStockBehavior: 'notifyMe',
        showQuantitySelector: true,
        showAddToCart: true,
        showBuyNow: true,
        showWishlist: true,
        showShare: true,
        showShippingInfo: true,
        shippingText: 'Free express shipping on all orders above $100',
        deliveryEstimatorEnabled: true,
        defaultEstimatedDays: '2-4 Business Days',
        showReturnsInfo: true,
        returnDays: 7,
        returnPolicyText: 'Hassle-free 7-day doorstep exchange and returns guarantee',
        trustBadges: [
          { id: 'auth', title: '100% Authentic Quality', desc: 'Direct from verified luxury ateliers', enabled: true },
          { id: 'shipping', title: 'Complimentary Express Shipping', desc: 'Dispatched in 24 hours', enabled: true },
          { id: 'exchange', title: '7-Day Easy Exchange', desc: 'Doorstep pickup available', enabled: true },
          { id: 'secure', title: 'Secure Protected Payment', desc: 'Encrypted SSL checkout', enabled: true },
        ],
        stickyDesktop: true,
        stickyOffsetPx: 80,
        mobileStickyBar: true,
      },
      sections: [
        { id: 'sec_tabs', type: 'tabs', title: 'Product Details & Dimensions', enabled: true, position: 1 },
        { id: 'sec_reviews', type: 'reviews', title: 'Customer Reviews & Ratings', enabled: true, position: 2 },
        { id: 'sec_related', type: 'relatedProducts', title: 'Complete the Look & Related Creations', enabled: true, position: 3 },
        { id: 'sec_recent', type: 'recentlyViewed', title: 'Recently Viewed', enabled: true, position: 4 },
      ],
      seo: {
        metaTitleTemplate: '{{product.title}} | Luxury Designer Wear',
        metaDescriptionTemplate: 'Shop the {{product.title}}. Handcrafted with premium textiles, bespoke tailoring, and timeless elegance.',
        enableJsonLd: true,
        canonicalStrategy: 'base-product',
      },
      accentColor: '#E11D48',
    },
  },

  minimal_studio: {
    name: 'Minimalist Scandinavian Studio',
    description: 'Clean stacked vertical imagery, 1:1 square media, high contrast typography, compact purchase panel, and sleek accordions.',
    config: {
      id: 'minimal_studio',
      name: 'Minimalist Scandinavian Studio',
      isDefault: false,
      gallery: {
        layout: 'stacked',
        aspectRatio: '1:1',
        zoomMode: 'click',
        thumbnailsPosition: 'hidden',
        enableVideo: false,
        enable360: false,
        galleryWidthPercent: 50,
        gap: 'large',
        mobileCarousel: true,
        showImageBadge: false,
      },
      purchasePanel: {
        elementsOrder: [
          'brand',
          'title',
          'price',
          'colorSwatches',
          'sizeSelector',
          'quantity',
          'addToCart',
          'buyNow',
          'shipping',
          'returns',
        ],
        showBrand: true,
        showTitle: true,
        showRating: false,
        showReviewCount: false,
        showPrice: true,
        showComparePrice: false,
        showDiscount: false,
        discountFormat: 'amount',
        showBadges: false,
        showSKU: false,
        colorDisplayType: 'chips',
        sizeDisplayType: 'chips',
        showStockStatus: false,
        showLowStockWarning: false,
        lowStockThreshold: 3,
        lowStockMessage: 'Limited stock',
        outOfStockBehavior: 'disabled',
        showQuantitySelector: true,
        showAddToCart: true,
        showBuyNow: false,
        showWishlist: true,
        showShare: false,
        showShippingInfo: true,
        shippingText: 'Standard worldwide shipping calculated at checkout',
        deliveryEstimatorEnabled: false,
        defaultEstimatedDays: '3-5 Days',
        showReturnsInfo: true,
        returnDays: 14,
        returnPolicyText: '14-day return policy',
        trustBadges: [],
        stickyDesktop: true,
        stickyOffsetPx: 100,
        mobileStickyBar: false,
      },
      sections: [
        { id: 'sec_accordions', type: 'accordions', title: 'Specifications & Care', enabled: true, position: 1 },
        { id: 'sec_related', type: 'relatedProducts', title: 'Curated Essentials', enabled: true, position: 2 },
      ],
      seo: {
        metaTitleTemplate: '{{product.title}} — Studio Collection',
        metaDescriptionTemplate: 'Explore the {{product.title}}. Minimalist form and exceptional materials.',
        enableJsonLd: true,
        canonicalStrategy: 'base-product',
      },
      accentColor: '#090D15',
    },
  },

  luxury_atelier: {
    name: 'Luxury Haute Couture & Atelier',
    description: 'High-drama 2-column masonry gallery, gold accents, private concierge instant buy, and artisan provenance certificate.',
    config: {
      id: 'luxury_atelier',
      name: 'Luxury Haute Couture & Atelier',
      isDefault: false,
      gallery: {
        layout: 'grid-2',
        aspectRatio: '4:5',
        zoomMode: 'fullscreen',
        thumbnailsPosition: 'bottom',
        enableVideo: true,
        enable360: true,
        galleryWidthPercent: 60,
        gap: 'large',
        mobileCarousel: true,
        showImageBadge: true,
      },
      purchasePanel: {
        elementsOrder: [
          'badges',
          'brand',
          'title',
          'rating',
          'price',
          'colorSwatches',
          'sizeSelector',
          'sizeGuide',
          'addToCart',
          'buyNow',
          'wishlist',
          'shipping',
          'returns',
        ],
        showBrand: true,
        showTitle: true,
        showRating: true,
        showReviewCount: true,
        showPrice: true,
        showComparePrice: true,
        showDiscount: true,
        discountFormat: 'percentage',
        showBadges: true,
        showSKU: true,
        colorDisplayType: 'swatches',
        sizeDisplayType: 'buttons',
        showStockStatus: true,
        showLowStockWarning: true,
        lowStockThreshold: 2,
        lowStockMessage: 'Atelier Limited Edition — Only {{quantity}} remaining',
        outOfStockBehavior: 'preorder',
        showQuantitySelector: false,
        showAddToCart: true,
        showBuyNow: true,
        showWishlist: true,
        showShare: true,
        showShippingInfo: true,
        shippingText: 'White-glove insured delivery included with all haute couture garments',
        deliveryEstimatorEnabled: true,
        defaultEstimatedDays: 'Express Air 48h',
        showReturnsInfo: true,
        returnDays: 7,
        returnPolicyText: 'Complimentary private courier returns and exchanges',
        trustBadges: [
          { id: 'prov', title: 'Artisan Provenance', desc: 'Hand-signed certificate of authenticity', enabled: true },
          { id: 'glove', title: 'White-Glove Shipping', desc: 'Silk packaging with luxury dust bag', enabled: true },
          { id: 'vip', title: 'Private Styling Access', desc: 'Direct atelier concierge support', enabled: true },
        ],
        stickyDesktop: true,
        stickyOffsetPx: 60,
        mobileStickyBar: true,
      },
      sections: [
        { id: 'sec_spec', type: 'specifications', title: 'Textile Composition & Handcrafting', enabled: true, position: 1 },
        { id: 'sec_reviews', type: 'reviews', title: 'Client Testimonials', enabled: true, position: 2 },
        { id: 'sec_related', type: 'relatedProducts', title: 'From the Same Runway Collection', enabled: true, position: 3 },
      ],
      seo: {
        metaTitleTemplate: '{{product.title}} | Haute Couture Atelier',
        metaDescriptionTemplate: 'Exclusive release: {{product.title}}. Discover bespoke tailoring, fine silks, and master craftsmanship.',
        enableJsonLd: true,
        canonicalStrategy: 'base-product',
      },
      accentColor: '#D4AF37',
    },
  },

  editorial_lookbook: {
    name: 'Editorial Storytelling Lookbook',
    description: 'Split editorial hero, large editorial typography, embedded designer notes, and runway storytelling modules.',
    config: {
      id: 'editorial_lookbook',
      name: 'Editorial Storytelling Lookbook',
      isDefault: false,
      gallery: {
        layout: 'masonry',
        aspectRatio: '3:4',
        zoomMode: 'hover',
        thumbnailsPosition: 'left',
        enableVideo: true,
        enable360: false,
        galleryWidthPercent: 55,
        gap: 'medium',
        mobileCarousel: true,
        showImageBadge: true,
      },
      purchasePanel: {
        elementsOrder: [...DEFAULT_PURCHASE_ELEMENTS_ORDER],
        showBrand: true,
        showTitle: true,
        showRating: true,
        showReviewCount: true,
        showPrice: true,
        showComparePrice: true,
        showDiscount: true,
        discountFormat: 'percentage',
        showBadges: true,
        showSKU: false,
        colorDisplayType: 'swatches',
        sizeDisplayType: 'buttons',
        showStockStatus: true,
        showLowStockWarning: true,
        lowStockThreshold: 4,
        lowStockMessage: 'Editorial release: {{quantity}} pieces left',
        outOfStockBehavior: 'notifyMe',
        showQuantitySelector: true,
        showAddToCart: true,
        showBuyNow: true,
        showWishlist: true,
        showShare: true,
        showShippingInfo: true,
        shippingText: 'Carbon-neutral delivery across all regions',
        deliveryEstimatorEnabled: true,
        defaultEstimatedDays: '2-3 Days',
        showReturnsInfo: true,
        returnDays: 10,
        returnPolicyText: '10-day seamless exchange',
        trustBadges: [
          { id: 'eco', title: 'Sustainable Sourcing', desc: '100% Organic eco-certified fibers', enabled: true },
          { id: 'ship', title: 'Climate Neutral Shipments', desc: 'Zero net carbon footprint', enabled: true },
        ],
        stickyDesktop: true,
        stickyOffsetPx: 80,
        mobileStickyBar: true,
      },
      sections: [
        { id: 'sec_desc', type: 'description', title: 'The Designer Notes', enabled: true, position: 1 },
        { id: 'sec_spec', type: 'specifications', title: 'Garment Details', enabled: true, position: 2 },
        { id: 'sec_reviews', type: 'reviews', title: 'Editorial Feedback', enabled: true, position: 3 },
        { id: 'sec_recs', type: 'recommendedProducts', title: 'Recommended by Our Stylists', enabled: true, position: 4 },
      ],
      seo: {
        metaTitleTemplate: '{{product.title}} — Editorial Feature',
        metaDescriptionTemplate: 'Read the story behind the {{product.title}}. Handcrafted silhouettes with modern attitude.',
        enableJsonLd: true,
        canonicalStrategy: 'base-product',
      },
      accentColor: '#9333EA',
    },
  },

  high_density_catalog: {
    name: 'High-Density Fast Checkout & Clearance',
    description: 'Carousel media, instant low-stock countdown, direct 1-click buy, and compact specification matrix.',
    config: {
      id: 'high_density_catalog',
      name: 'High-Density Fast Checkout',
      isDefault: false,
      gallery: {
        layout: 'carousel',
        aspectRatio: '1:1',
        zoomMode: 'hover',
        thumbnailsPosition: 'bottom',
        enableVideo: false,
        enable360: false,
        galleryWidthPercent: 45,
        gap: 'small',
        mobileCarousel: true,
        showImageBadge: true,
      },
      purchasePanel: {
        elementsOrder: [
          'badges',
          'title',
          'price',
          'stockUrgency',
          'colorSwatches',
          'sizeSelector',
          'quantity',
          'buyNow',
          'addToCart',
          'shipping',
        ],
        showBrand: false,
        showTitle: true,
        showRating: true,
        showReviewCount: true,
        showPrice: true,
        showComparePrice: true,
        showDiscount: true,
        discountFormat: 'percentage',
        showBadges: true,
        showSKU: true,
        colorDisplayType: 'chips',
        sizeDisplayType: 'chips',
        showStockStatus: true,
        showLowStockWarning: true,
        lowStockThreshold: 10,
        lowStockMessage: '⚡ Flash Deal: Only {{quantity}} units remaining at this price!',
        outOfStockBehavior: 'disabled',
        showQuantitySelector: true,
        showAddToCart: true,
        showBuyNow: true,
        showWishlist: true,
        showShare: true,
        showShippingInfo: true,
        shippingText: '⚡ Same-day dispatch on orders before 2 PM',
        deliveryEstimatorEnabled: true,
        defaultEstimatedDays: 'Next Day Delivery',
        showReturnsInfo: true,
        returnDays: 7,
        returnPolicyText: 'Instant replacement on transit issues',
        trustBadges: [],
        stickyDesktop: true,
        stickyOffsetPx: 50,
        mobileStickyBar: true,
      },
      sections: [
        { id: 'sec_spec', type: 'specifications', title: 'Product Specifications Table', enabled: true, position: 1 },
        { id: 'sec_reviews', type: 'reviews', title: 'Customer Ratings', enabled: true, position: 2 },
        { id: 'sec_related', type: 'relatedProducts', title: 'Similar Flash Deals', enabled: true, position: 3 },
      ],
      seo: {
        metaTitleTemplate: 'Buy {{product.title}} Online | Best Price Guarantee',
        metaDescriptionTemplate: 'Order {{product.title}} now with fast delivery and warranty protection.',
        enableJsonLd: true,
        canonicalStrategy: 'base-product',
      },
      accentColor: '#F59E0B',
    },
  },
};

export function getDefaultPdpConfig(tenantSlug: string = 'default'): ProductPageConfig {
  return JSON.parse(JSON.stringify(PDP_PRESET_TEMPLATES.default_fashion.config));
}
