import { MongoClient } from 'mongodb';
import * as fs from 'fs';
import * as path from 'path';

// Load .env.local
const envPath = path.resolve(process.cwd(), '.env.local');
if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf8');
  for (const line of envContent.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx > 0) {
      const key = trimmed.substring(0, eqIdx).trim();
      const val = trimmed.substring(eqIdx + 1).trim();
      if (!process.env[key]) {
        process.env[key] = val;
      }
    }
  }
}

const uri = process.env.MONGODB_URI || process.env.MONGO_URI || '';
if (!uri) {
  console.error('❌ MONGODB_URI not found');
  process.exit(1);
}

interface CategoryDemoDef {
  slug: string;
  name: string;
  category: string;
  categoryLabel: string;
  tagline: string;
  primaryColor: string;
  accentColor: string;
  secondaryColor: string;
  headingFont: string;
  bodyFont: string;
  planId: string;
  planName: string;
  ownerName: string;
  ownerEmail: string;
  categories: { id: string; name: string; slug: string; description: string; image: string }[];
  products: any[];
}

export const CATEGORY_DEMO_STORES: CategoryDemoDef[] = [
  {
    slug: 'demo-fashion',
    name: 'Lumina Luxury Fashion Atelier',
    category: 'fashion',
    categoryLabel: '👗 Fashion & Luxury Apparel',
    tagline: 'Curated High-End Designer Fashion, Heritage Sarees & Contemporary Tailoring',
    primaryColor: '#0F172A',
    accentColor: '#E11D48',
    secondaryColor: '#FFFFFF',
    headingFont: 'Playfair Display',
    bodyFont: 'Plus Jakarta Sans',
    planId: 'plan_enterprise',
    planName: 'Enterprise SaaS Tier',
    ownerName: 'Victoria Sterling',
    ownerEmail: 'fashion-demo@mavenco.cloud',
    categories: [
      { id: 'cat_fash_1', name: 'Royal Sarees', slug: 'sarees', description: 'Heirloom handwoven pure silk Banarasi and Kanjivaram sarees', image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_fash_2', name: 'Atelier Tailoring', slug: 'blazers', description: 'Italian velvet blazers and bespoke evening tuxedos', image: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_fash_3', name: 'Evening Gowns', slug: 'dresses', description: 'Flowing French chiffon and couture evening dresses', image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_fash_4', name: 'Luxury Handbags', slug: 'handbags', description: 'Italian handcrafted calfskin shoulder and tote bags', image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=1000&auto=format&fit=crop' },
    ],
    products: [
      {
        name: 'Pure Mulberry Silk Banarasi Saree',
        slug: 'pure-mulberry-silk-banarasi-saree-demo-fashion',
        sku: 'FSH-SAR-001',
        department: 'women',
        category: 'sarees',
        categoryName: 'Royal Sarees',
        price: 14999,
        compareAtPrice: 19999,
        discountPercent: 25,
        shortDescription: 'Heirloom handwoven pure Katan silk saree with real gold zari kadwa motifs.',
        description: 'A masterpiece of Banarasi handloom artistry. Woven over 45 days by generational weavers using certified pure mulberry silk and antique gold zari borders.',
        features: ['100% Pure Katan Silk certified SilkMark', 'Intricate floral kadwa zari jaal throughout body', 'Includes unstitched running silk blouse piece (80cm)'],
        fabric: 'Pure Mulberry Silk & Gold Zari',
        careInstructions: ['Strictly Dry Clean Only'],
        images: [{ url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1000&auto=format&fit=crop', alt: 'Silk Saree Front', isPrimary: true }],
        colors: [{ name: 'Imperial Crimson', hex: '#8B0000' }, { name: 'Royal Emerald', hex: '#004B23' }],
        sizes: [{ size: 'Free Size', inStock: true, stockCount: 15 }],
        rating: 5.0,
        reviewCount: 48,
        isFeatured: true,
        isNewArrival: true,
        isBestSeller: true,
        badge: 'Heirloom Heritage',
      },
      {
        name: 'Artisanal Embroidered Velvet Tuxedo Blazer',
        slug: 'artisanal-embroidered-velvet-tuxedo-blazer-demo-fashion',
        sku: 'FSH-BLZ-002',
        department: 'women',
        category: 'blazers',
        categoryName: 'Atelier Tailoring',
        price: 8999,
        compareAtPrice: 12499,
        discountPercent: 28,
        shortDescription: 'Midnight sapphire plush micro-velvet blazer with hand-zardozi peak lapels.',
        description: 'Statement evening tailoring at its finest. Cut from Italian micro-velvet with a sharp structured shoulder line and opulent metallic thread work.',
        features: ['Plush Italian cotton micro-velvet', 'Hand-stitched metallic zardozi lapel embroidery'],
        fabric: 'Italian Velvet & Silk Satin Lining',
        careInstructions: ['Specialist Dry Clean Only'],
        images: [{ url: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=1000&auto=format&fit=crop', alt: 'Velvet Tuxedo Blazer', isPrimary: true }],
        colors: [{ name: 'Midnight Sapphire', hex: '#0F1E36' }, { name: 'Wine Velvet', hex: '#4A0E17' }],
        sizes: [{ size: 'S', inStock: true, stockCount: 8 }, { size: 'M', inStock: true, stockCount: 12 }, { size: 'L', inStock: true, stockCount: 6 }],
        rating: 4.9,
        reviewCount: 38,
        isFeatured: true,
        isNewArrival: false,
        isBestSeller: true,
        badge: 'Atelier Drop',
      },
      {
        name: 'French Chiffon Pleated Evening Gown',
        slug: 'french-chiffon-pleated-evening-gown-demo-fashion',
        sku: 'FSH-DRS-003',
        department: 'women',
        category: 'dresses',
        categoryName: 'Evening Gowns',
        price: 7499,
        compareAtPrice: 10200,
        discountPercent: 26,
        shortDescription: 'Airy pleated silk chiffon gown with a defined waistline and flowing train.',
        description: 'Effortless red-carpet glamour. Crafted with micro-accordion pleating and an inner corset support structure for flawless silhouette sculpting.',
        features: ['Air-weight French Chiffon', 'Concealed internal corsetry and padded cups'],
        fabric: '100% Silk Chiffon',
        careInstructions: ['Dry Clean Only'],
        images: [{ url: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=1000&auto=format&fit=crop', alt: 'Chiffon Evening Gown', isPrimary: true }],
        colors: [{ name: 'Champagne Blush', hex: '#F7E7CE' }, { name: 'Noir Onyx', hex: '#111111' }],
        sizes: [{ size: 'XS', inStock: true, stockCount: 4 }, { size: 'S', inStock: true, stockCount: 10 }, { size: 'M', inStock: true, stockCount: 8 }],
        rating: 4.8,
        reviewCount: 29,
        isFeatured: true,
        isNewArrival: true,
        badge: 'New Season',
      },
      {
        name: 'Italian Calfskin Quilted Shoulder Bag',
        slug: 'italian-calfskin-quilted-shoulder-bag-demo-fashion',
        sku: 'FSH-BAG-004',
        department: 'women',
        category: 'handbags',
        categoryName: 'Luxury Handbags',
        price: 11200,
        compareAtPrice: 15000,
        discountPercent: 25,
        shortDescription: 'Chevron quilted supple calfskin with heavy gold-plated twist lock hardware.',
        description: 'Timeless luxury accessory featuring hand-stitched chevron quilting and an adjustable chain strap for shoulder or crossbody styling.',
        features: ['Full-grain Italian calfskin', '24K gold electroplated hardware', 'Burgundy leather interior lining'],
        fabric: 'Italian Calf Leather',
        careInstructions: ['Wipe with clean soft leather cloth'],
        images: [{ url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=1000&auto=format&fit=crop', alt: 'Quilted Shoulder Bag', isPrimary: true }],
        colors: [{ name: 'Black Caviar', hex: '#1A1A1A' }, { name: 'Warm Taupe', hex: '#B38B6D' }],
        sizes: [{ size: 'One Size (25cm)', inStock: true, stockCount: 14 }],
        rating: 5.0,
        reviewCount: 52,
        isFeatured: true,
        isBestSeller: true,
        badge: 'Iconic Bag',
      },
    ],
  },
  {
    slug: 'demo-electronics',
    name: 'VoltTech Audio & Smart Gadgets',
    category: 'electronics',
    categoryLabel: '⚡ Electronics & Smart Gadgets',
    tagline: 'Active Noise Cancelling Studio Audio, Smart Wearables & Flagship Power Docks',
    primaryColor: '#0A0F1D',
    accentColor: '#06B6D4',
    secondaryColor: '#0F172A',
    headingFont: 'Outfit',
    bodyFont: 'Inter',
    planId: 'plan_pro',
    planName: 'Professional Scale',
    ownerName: 'Marcus Vance',
    ownerEmail: 'electronics-demo@mavenco.cloud',
    categories: [
      { id: 'cat_elec_1', name: 'Studio Audio', slug: 'audio', description: 'Hi-Res certified wireless headphones and audiophile gear', image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_elec_2', name: 'Smart Wearables', slug: 'wearables', description: 'Titanium smartwatches and biometrics health bands', image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_elec_3', name: 'GaN Chargers & Docks', slug: 'power', description: 'Ultra-fast gallium nitride chargers and magnetic multi-device docks', image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_elec_4', name: 'Smart Home Audio', slug: 'smarthome', description: 'Spatial soundbars and multi-room wireless audio systems', image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?q=80&w=1000&auto=format&fit=crop' },
    ],
    products: [
      {
        name: 'Volt Pro Wireless ANC Studio Headphones',
        slug: 'volt-pro-wireless-anc-studio-headphones-demo-electronics',
        sku: 'VLT-AUD-001',
        department: 'electronics',
        category: 'audio',
        categoryName: 'Studio Audio',
        price: 18999,
        compareAtPrice: 24999,
        discountPercent: 24,
        shortDescription: 'Hybrid Active Noise Cancellation with custom 45mm beryllium drivers and 65hr battery.',
        description: 'Engineered for audiophiles and music producers. Features lossless LDAC audio streaming, dual transparency mode, and ultra-plush memory foam earcups.',
        features: ['45mm custom Beryllium acoustic drivers', '-42dB Hybrid Active Noise Cancellation', '65-Hour battery playback with fast charge (10m = 5h)'],
        fabric: 'Aerospace Aluminium & Protein Leather',
        careInstructions: ['Store in included hard shell travel case'],
        images: [{ url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1000&auto=format&fit=crop', alt: 'Volt Pro Headphones', isPrimary: true }],
        colors: [{ name: 'Midnight Space Gray', hex: '#2A2E39' }, { name: 'Polar Silver', hex: '#D8D9DD' }],
        sizes: [{ size: 'Over-Ear', inStock: true, stockCount: 25 }],
        rating: 4.9,
        reviewCount: 94,
        isFeatured: true,
        isBestSeller: true,
        badge: 'Flagship Audio',
      },
      {
        name: 'Apex Ultra Titanium GPS Smartwatch',
        slug: 'apex-ultra-titanium-gps-smartwatch-demo-electronics',
        sku: 'VLT-WAT-002',
        department: 'electronics',
        category: 'wearables',
        categoryName: 'Smart Wearables',
        price: 14499,
        compareAtPrice: 18999,
        discountPercent: 23,
        shortDescription: 'Aerospace grade Grade 5 titanium chassis, sapphire crystal display, dual-frequency GPS.',
        description: 'Rugged outdoor smartwatch with ECG heart rate tracking, blood oxygen analytics, 100m water resistance, and up to 14 days standby battery.',
        features: ['Grade 5 Titanium bezel & sapphire crystal', 'Dual-frequency multi-satellite GPS navigation', '100m water-resistant with diving mode'],
        fabric: 'Titanium & Fluoroelastomer Sport Strap',
        careInstructions: ['Rinse with fresh water after ocean swimming'],
        images: [{ url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1000&auto=format&fit=crop', alt: 'Apex Titanium Smartwatch', isPrimary: true }],
        colors: [{ name: 'Titanium Slate', hex: '#4A5568' }, { name: 'Carbon Black', hex: '#1A202C' }],
        sizes: [{ size: '49mm Bezel', inStock: true, stockCount: 18 }],
        rating: 4.9,
        reviewCount: 76,
        isFeatured: true,
        isNewArrival: true,
        badge: 'Titanium Build',
      },
      {
        name: '140W 4-Port GaN Fast Charger & MagSafe Dock',
        slug: '140w-4-port-gan-fast-charger-demo-electronics',
        sku: 'VLT-PWR-003',
        department: 'electronics',
        category: 'power',
        categoryName: 'GaN Chargers & Docks',
        price: 4299,
        compareAtPrice: 5999,
        discountPercent: 28,
        shortDescription: 'Next-gen Gallium Nitride 140W PD 3.1 charging station for laptops, phones and watches.',
        description: 'Power up to 4 high-demand devices simultaneously at maximum speed without thermal throttling. Compact foldable prongs for worldwide travel.',
        features: ['GaN III Semiconductor architecture', '140W USB-C Power Delivery 3.1 output', 'Active temperature monitoring 80,000 times/hr'],
        fabric: 'Fireproof Polycarbonate Case',
        careInstructions: ['Keep away from liquids and moisture'],
        images: [{ url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?q=80&w=1000&auto=format&fit=crop', alt: 'GaN Fast Charger', isPrimary: true }],
        colors: [{ name: 'Matte Stealth', hex: '#212529' }],
        sizes: [{ size: 'Universal Desktop', inStock: true, stockCount: 40 }],
        rating: 4.8,
        reviewCount: 61,
        isFeatured: true,
        badge: 'GaN III Tech',
      },
      {
        name: 'High-Res Spatial Audio Bluetooth Soundbar',
        slug: 'high-res-spatial-audio-soundbar-demo-electronics',
        sku: 'VLT-SND-004',
        department: 'electronics',
        category: 'smarthome',
        categoryName: 'Smart Home Audio',
        price: 12800,
        compareAtPrice: 16999,
        discountPercent: 24,
        shortDescription: 'Dolby Atmos cinematic 3.1.2 channel soundbar with integrated wireless subwoofers.',
        description: 'Transforms movie nights and gaming with room-filling spatial acoustic beam-forming and ultra-crisp dialog clarity.',
        features: ['True Dolby Atmos 3.1.2 sound architecture', 'HDMI eARC & Optical lossless connection', 'Bluetooth 5.3 & AirPlay 2 streaming'],
        fabric: 'Acoustic Mesh & Brushed Aluminium',
        careInstructions: ['Dust with soft dry cloth'],
        images: [{ url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?q=80&w=1000&auto=format&fit=crop', alt: 'Spatial Soundbar', isPrimary: true }],
        colors: [{ name: 'Obsidian Black', hex: '#111827' }],
        sizes: [{ size: '900mm Bar', inStock: true, stockCount: 12 }],
        rating: 4.9,
        reviewCount: 43,
        isFeatured: true,
        badge: 'Dolby Atmos',
      },
    ],
  },
  {
    slug: 'demo-home',
    name: 'Aura Modern Living & Furniture',
    category: 'home',
    categoryLabel: '🛋️ Home, Furniture & Modern Living',
    tagline: 'Artisanal Home Decor, Sustainable Solid Wood Furniture & Scandinavian Interior',
    primaryColor: '#1C1917',
    accentColor: '#D97706',
    secondaryColor: '#FAFAF9',
    headingFont: 'Playfair Display',
    bodyFont: 'Plus Jakarta Sans',
    planId: 'plan_pro',
    planName: 'Professional Scale',
    ownerName: 'Evelyn Reed',
    ownerEmail: 'home-demo@mavenco.cloud',
    categories: [
      { id: 'cat_home_1', name: 'Artisanal Decor', slug: 'decor', description: 'Sculptural stoneware ceramic vases and minimalist tabletop decor', image: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_home_2', name: 'Designer Furniture', slug: 'furniture', description: 'Mid-century modern teakwood armchairs, tables and consoles', image: 'https://images.unsplash.com/photo-1580481077197-0ec997bca314?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_home_3', name: 'Architectural Lighting', slug: 'lighting', description: 'Brushed brass floor lamps and pendant fixtures', image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_home_4', name: 'Handwoven Rugs', slug: 'rugs', description: 'Nordic wool textured floor rugs and artisanal tapestries', image: 'https://images.unsplash.com/photo-1600121848594-d8644e57abab?q=80&w=1000&auto=format&fit=crop' },
    ],
    products: [
      {
        name: 'Handcrafted Fluted Ceramic Vase',
        slug: 'handcrafted-fluted-ceramic-vase-demo-home',
        sku: 'HOM-VAS-001',
        department: 'home',
        category: 'decor',
        categoryName: 'Artisanal Decor',
        price: 2499,
        compareAtPrice: 3499,
        discountPercent: 28,
        shortDescription: 'Minimalist Scandinavian ceramic vase with matte chalk glaze finish.',
        description: 'Elevate your living space with this sculptural fluted ceramic vase. Perfect for dried botanical arrangements or as a standalone architectural tabletop piece.',
        features: ['100% High-fire stoneware clay', 'Waterproof interior glaze', 'Hand-grooved vertical fluting'],
        fabric: 'Matte Glazed Stoneware',
        careInstructions: ['Wipe with damp microfiber cloth'],
        images: [{ url: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?q=80&w=1000&auto=format&fit=crop', alt: 'Ceramic Vase', isPrimary: true }],
        colors: [{ name: 'Chalk White', hex: '#F5F5F3' }, { name: 'Earthy Terracotta', hex: '#C86D51' }],
        sizes: [{ size: 'Medium (30cm)', inStock: true, stockCount: 22 }],
        rating: 4.9,
        reviewCount: 68,
        isFeatured: true,
        isBestSeller: true,
        badge: 'Best Seller',
      },
      {
        name: 'Mid-Century Modern Teakwood Lounge Armchair',
        slug: 'mid-century-teakwood-lounge-armchair-demo-home',
        sku: 'HOM-CHR-002',
        department: 'home',
        category: 'furniture',
        categoryName: 'Designer Furniture',
        price: 19500,
        compareAtPrice: 26000,
        discountPercent: 25,
        shortDescription: 'Solid kiln-dried Indonesian teakwood frame with natural oatmeal boucle upholstery.',
        description: 'Timeless ergonomic silhouette designed for hours of comfortable reading and conversation. Mortise-and-tenon joinery built to last generations.',
        features: ['Sustainably sourced Grade-A Teakwood', 'High-resilience foam core with textured boucle wrap'],
        fabric: 'Solid Teak & Boucle Fabric',
        careInstructions: ['Professional upholstery cleaner only'],
        images: [{ url: 'https://images.unsplash.com/photo-1580481077197-0ec997bca314?q=80&w=1000&auto=format&fit=crop', alt: 'Teakwood Armchair', isPrimary: true }],
        colors: [{ name: 'Natural Oatmeal', hex: '#EAE6DF' }, { name: 'Olive Green', hex: '#556B2F' }],
        sizes: [{ size: 'Standard Lounge', inStock: true, stockCount: 7 }],
        rating: 5.0,
        reviewCount: 34,
        isFeatured: true,
        badge: 'Solid Wood',
      },
      {
        name: 'Brushed Brass Minimalist Arc Floor Lamp',
        slug: 'brushed-brass-minimalist-arc-floor-lamp-demo-home',
        sku: 'HOM-LMP-003',
        department: 'home',
        category: 'lighting',
        categoryName: 'Architectural Lighting',
        price: 7800,
        compareAtPrice: 10500,
        discountPercent: 25,
        shortDescription: 'Heavy marble base with slender adjustable brushed brass arc and warm LED shade.',
        description: 'Sweeps gracefully over sofas or reading corners to provide glare-free ambient illumination. Features an integrated foot-step dimmer switch.',
        features: ['Real Carrara marble weighted base (12kg)', 'Warm 2700K flicker-free LED bulb included'],
        fabric: 'Solid Brass & Carrara Marble',
        careInstructions: ['Clean with dry microfiber towel'],
        images: [{ url: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=1000&auto=format&fit=crop', alt: 'Arc Floor Lamp', isPrimary: true }],
        colors: [{ name: 'Brushed Antique Brass', hex: '#D4AF37' }],
        sizes: [{ size: 'Height 185cm', inStock: true, stockCount: 15 }],
        rating: 4.8,
        reviewCount: 41,
        isFeatured: true,
        badge: 'Marble Base',
      },
      {
        name: 'Handwoven Pure Wool Textured Nordic Rug',
        slug: 'handwoven-wool-textured-nordic-rug-demo-home',
        sku: 'HOM-RUG-004',
        department: 'home',
        category: 'rugs',
        categoryName: 'Handwoven Rugs',
        price: 13999,
        compareAtPrice: 18500,
        discountPercent: 24,
        shortDescription: '100% New Zealand pure virgin wool with high-low loop pile textural pattern.',
        description: 'Luxuriously soft underfoot with natural stain resistance. Hand-knotted by master artisans using un-dyed organic wool fibers.',
        features: ['100% Certified New Zealand Wool', 'High-density 4000g/sqm luxurious pile weight'],
        fabric: 'Pure New Zealand Wool',
        careInstructions: ['Vacuum regularly on low suction setting'],
        images: [{ url: 'https://images.unsplash.com/photo-1600121848594-d8644e57abab?q=80&w=1000&auto=format&fit=crop', alt: 'Nordic Wool Rug', isPrimary: true }],
        colors: [{ name: 'Ivory Cream', hex: '#FDFBF7' }, { name: 'Heather Gray', hex: '#9E9E9E' }],
        sizes: [{ size: '5x8 Feet', inStock: true, stockCount: 10 }, { size: '8x10 Feet', inStock: true, stockCount: 6 }],
        rating: 4.9,
        reviewCount: 56,
        isFeatured: true,
        badge: 'Pure Wool',
      },
    ],
  },
  {
    slug: 'demo-beauty',
    name: 'GlowBotanica Luxury Skincare',
    category: 'beauty',
    categoryLabel: '💄 Beauty, Cosmetics & Skincare',
    tagline: 'Clean Botanical Serums, Certified Organic Actives & Luxury Fragrances',
    primaryColor: '#190F16',
    accentColor: '#EC4899',
    secondaryColor: '#FFF1F2',
    headingFont: 'Playfair Display',
    bodyFont: 'Plus Jakarta Sans',
    planId: 'plan_pro',
    planName: 'Professional Scale',
    ownerName: 'Clara Delacroix',
    ownerEmail: 'beauty-demo@mavenco.cloud',
    categories: [
      { id: 'cat_bty_1', name: 'Active Serums', slug: 'serums', description: 'Cold-pressed antioxidant serums and clinical grade peptides', image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_bty_2', name: 'Hydrating Creams', slug: 'creams', description: 'Deep barrier restoration creams and rose petal night balms', image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_bty_3', name: 'Artisanal Perfumes', slug: 'fragrances', description: 'Handcrafted niche fragrances blended in Grasse, France', image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_bty_4', name: 'Lip & Eye Care', slug: 'lip-care', description: 'Peptide plumpers and velvet hydrating lip stains', image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=1000&auto=format&fit=crop' },
    ],
    products: [
      {
        name: 'Botanical Radiance C-Elixir Face Serum',
        slug: 'botanical-radiance-c-elixir-face-serum-demo-beauty',
        sku: 'BTY-SRM-001',
        department: 'beauty',
        category: 'serums',
        categoryName: 'Active Serums',
        price: 3299,
        compareAtPrice: 4500,
        discountPercent: 26,
        shortDescription: '15% Stabilized Vitamin C, Ferulic Acid and Botanical Kakadu Plum extract.',
        description: 'Clinically proven to boost skin luminescence, fade dark spots, and defend against environmental stressors with a featherweight dry-oil finish.',
        features: ['15% Potent active Vitamin C (THD Ascorbate)', 'Wild-harvested Australian Kakadu Plum', '100% Vegan & Cruelty Free certified'],
        fabric: 'Glass Dropper Vial (30ml)',
        careInstructions: ['Store in a cool dark place away from direct sunlight'],
        images: [{ url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=1000&auto=format&fit=crop', alt: 'Radiance Serum Bottle', isPrimary: true }],
        colors: [{ name: 'Amber Gold', hex: '#FFBF00' }],
        sizes: [{ size: '30ml / 1.0 fl. oz', inStock: true, stockCount: 35 }],
        rating: 4.9,
        reviewCount: 112,
        isFeatured: true,
        isBestSeller: true,
        badge: 'Award Winner',
      },
      {
        name: 'Midnight Damask Rose Rejuvenating Night Cream',
        slug: 'midnight-damask-rose-night-cream-demo-beauty',
        sku: 'BTY-CRM-002',
        department: 'beauty',
        category: 'creams',
        categoryName: 'Hydrating Creams',
        price: 4199,
        compareAtPrice: 5600,
        discountPercent: 25,
        shortDescription: 'Rich velvet ceramide barrier balm infused with Bulgarian Damask Rose distillate.',
        description: 'Wakes up tired, parched skin with intensive multi-molecular hyaluronic hydration and barrier-repairing lipid complexes.',
        features: ['5 Essential Ceramides complex', 'Cold-distilled Bulgarian Rose Damascena essence'],
        fabric: 'Frosted Glass Jar (50ml)',
        careInstructions: ['Apply generously to cleansed skin before bed'],
        images: [{ url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=1000&auto=format&fit=crop', alt: 'Night Cream Jar', isPrimary: true }],
        colors: [{ name: 'Blush Cream', hex: '#FFE4E1' }],
        sizes: [{ size: '50ml / 1.7 oz', inStock: true, stockCount: 28 }],
        rating: 5.0,
        reviewCount: 84,
        isFeatured: true,
        badge: 'Intense Repair',
      },
      {
        name: 'Santal & Cardamom Artisanal Eau De Parfum',
        slug: 'santal-cardamom-artisanal-eau-de-parfum-demo-beauty',
        sku: 'BTY-PRF-003',
        department: 'beauty',
        category: 'fragrances',
        categoryName: 'Artisanal Perfumes',
        price: 5800,
        compareAtPrice: 7500,
        discountPercent: 22,
        shortDescription: 'Creamy Australian sandalwood, crushed cardamom pods, and smoky ambergris.',
        description: 'An alluring genderless fragrance with extraordinary 14-hour longevity. Blended by master noses using 22% concentrated perfume oil.',
        features: ['22% Extrait de Parfum concentration', 'Organic sugarcane alcohol base', 'Magnetic heavy zamac cap'],
        fabric: 'Heavy Flacon (100ml)',
        careInstructions: ['Keep cap closed securely'],
        images: [{ url: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?q=80&w=1000&auto=format&fit=crop', alt: 'Eau de Parfum Flacon', isPrimary: true }],
        colors: [{ name: 'Smoky Amber', hex: '#FF7E00' }],
        sizes: [{ size: '100ml / 3.4 oz', inStock: true, stockCount: 19 }],
        rating: 4.9,
        reviewCount: 65,
        isFeatured: true,
        badge: 'Niche Scent',
      },
      {
        name: 'Velvet Matte Hydrating Peptide Lipstick',
        slug: 'velvet-matte-hydrating-peptide-lipstick-demo-beauty',
        sku: 'BTY-LIP-004',
        department: 'beauty',
        category: 'lip-care',
        categoryName: 'Lip & Eye Care',
        price: 1699,
        compareAtPrice: 2299,
        discountPercent: 26,
        shortDescription: 'Cushion comfort matte lipstick packed with plumping biomimetic peptides.',
        description: 'Delivers full color impact in a single swipe without cracking or feathering. Formulated with shea butter and plant squalane.',
        features: ['12-Hour smudge-proof wear', 'Infused with Maxi-Lip volumizing peptide'],
        fabric: 'Magnetic Metal Lipstick Bullet',
        careInstructions: ['Store at room temperature'],
        images: [{ url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=1000&auto=format&fit=crop', alt: 'Matte Lipstick Bullet', isPrimary: true }],
        colors: [{ name: 'Berry Noir', hex: '#4A1525' }, { name: 'Rose Nude', hex: '#C48A85' }],
        sizes: [{ size: '3.8g', inStock: true, stockCount: 45 }],
        rating: 4.8,
        reviewCount: 78,
        isFeatured: true,
        badge: 'Non-Drying',
      },
    ],
  },
  {
    slug: 'demo-fitness',
    name: 'Apex Athletics Performance',
    category: 'activewear',
    categoryLabel: '🏃 Sports, Gym & Activewear',
    tagline: 'Engineered Compressive Activewear, Carbon Runners & Training Equipment',
    primaryColor: '#09090B',
    accentColor: '#F97316',
    secondaryColor: '#18181B',
    headingFont: 'Outfit',
    bodyFont: 'Inter',
    planId: 'plan_pro',
    planName: 'Professional Scale',
    ownerName: 'Jordan Keller',
    ownerEmail: 'fitness-demo@mavenco.cloud',
    categories: [
      { id: 'cat_fit_1', name: 'Tights & Leggings', slug: 'bottoms', description: 'Squat-proof compressive gym tights and running shorts', image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_fit_2', name: 'Performance Tops', slug: 'tops', description: 'Thermal zip jackets, sweat-wicking tees and sports bras', image: 'https://images.unsplash.com/photo-1556817411-31ae72fa3ea0?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_fit_3', name: 'Running Footwear', slug: 'footwear', description: 'Carbon-plated marathon racing trainers and trail shoes', image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_fit_4', name: 'Training Equipment', slug: 'gear', description: 'Cast iron kettlebells, speed jump ropes and gym duffles', image: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?q=80&w=1000&auto=format&fit=crop' },
    ],
    products: [
      {
        name: 'Apex Pro Seamless High-Waist Leggings',
        slug: 'apex-pro-seamless-high-waist-leggings-demo-fitness',
        sku: 'ACT-LEG-001',
        department: 'fitness',
        category: 'bottoms',
        categoryName: 'Tights & Leggings',
        price: 2899,
        compareAtPrice: 3999,
        discountPercent: 27,
        shortDescription: 'Squat-proof 4-way stretch compressive tights with ribbed tummy control.',
        description: 'Engineered for intense weightlifting, HIIT, and sprint sessions. Seamless micro-ribbed contours flatter the physique while ensuring zero chafing.',
        features: ['100% Squat-proof ultra-high density knit', 'Core-sculpting ribbed compression waistband', 'Sweat-wicking SilverIon anti-odor tech'],
        fabric: '78% Recycled Nylon, 22% Elastane',
        careInstructions: ['Machine wash cold inside out'],
        images: [{ url: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=1000&auto=format&fit=crop', alt: 'Apex Seamless Leggings', isPrimary: true }],
        colors: [{ name: 'Obsidian Black', hex: '#1A1A1A' }, { name: 'Hyper Orange', hex: '#FF6F00' }],
        sizes: [{ size: 'S', inStock: true, stockCount: 24 }, { size: 'M', inStock: true, stockCount: 30 }, { size: 'L', inStock: true, stockCount: 16 }],
        rating: 4.9,
        reviewCount: 124,
        isFeatured: true,
        isBestSeller: true,
        badge: 'Pro Tier',
      },
      {
        name: 'Thermal Hyper-Vent Running Zip Jacket',
        slug: 'thermal-hyper-vent-running-zip-jacket-demo-fitness',
        sku: 'ACT-JKT-002',
        department: 'fitness',
        category: 'tops',
        categoryName: 'Performance Tops',
        price: 3799,
        compareAtPrice: 4999,
        discountPercent: 24,
        shortDescription: 'Windproof, water-resistant athletic jacket with laser-cut underarm ventilation.',
        description: 'Designed for cold-weather road running. Features 360-degree reflective accents, thumb loops, and a water-resistant zippered media pocket.',
        features: ['DWR storm-resistant finish', '360° NightVision high-reflectivity strips'],
        fabric: '100% Ripstop Poly with DWR',
        careInstructions: ['Machine wash gentle cycle'],
        images: [{ url: 'https://images.unsplash.com/photo-1556817411-31ae72fa3ea0?q=80&w=1000&auto=format&fit=crop', alt: 'Running Jacket', isPrimary: true }],
        colors: [{ name: 'Carbon Gray', hex: '#374151' }, { name: 'Blaze Orange', hex: '#EA580C' }],
        sizes: [{ size: 'S', inStock: true, stockCount: 12 }, { size: 'M', inStock: true, stockCount: 18 }, { size: 'L', inStock: true, stockCount: 14 }],
        rating: 4.8,
        reviewCount: 67,
        isFeatured: true,
        badge: 'StormProof',
      },
      {
        name: 'Carbon-Plate Dynamic Long-Distance Trainers',
        slug: 'carbon-plate-dynamic-distance-trainers-demo-fitness',
        sku: 'ACT-SHOE-003',
        department: 'fitness',
        category: 'footwear',
        categoryName: 'Running Footwear',
        price: 9999,
        compareAtPrice: 13500,
        discountPercent: 26,
        shortDescription: 'Full-length curved carbon plate with supercritical nitrogen-infused foam midsole.',
        description: 'Propels you forward on race day with unmatched 85% energy return. Breathable monomesh upper locks down the foot during PR attempts.',
        features: ['Full curved 3K Carbon Fiber plate', 'Supercritical NitroFoam with 85% energy return'],
        fabric: 'Engineered Monomesh & Carbon Plate',
        careInstructions: ['Air dry only, do not tumble dry'],
        images: [{ url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000&auto=format&fit=crop', alt: 'Carbon Running Shoes', isPrimary: true }],
        colors: [{ name: 'Apex Crimson', hex: '#DC2626' }],
        sizes: [{ size: 'UK 8', inStock: true, stockCount: 8 }, { size: 'UK 9', inStock: true, stockCount: 15 }, { size: 'UK 10', inStock: true, stockCount: 10 }],
        rating: 5.0,
        reviewCount: 89,
        isFeatured: true,
        badge: 'Race Day Pro',
      },
      {
        name: 'Matte Cast Iron Precision Kettlebell (16kg)',
        slug: 'matte-cast-iron-precision-kettlebell-demo-fitness',
        sku: 'ACT-EQP-004',
        department: 'fitness',
        category: 'gear',
        categoryName: 'Training Equipment',
        price: 4899,
        compareAtPrice: 6500,
        discountPercent: 24,
        shortDescription: 'Single-piece gravity cast iron with chip-resistant matte powder coating.',
        description: 'Machined flat base prevents rolling during floor work. Color-coded handle rings for instantaneous weight identification.',
        features: ['Single-piece solid casting with zero seams', 'Grip-friendly matte black powder coat'],
        fabric: 'Solid Cast Iron',
        careInstructions: ['Wipe clean with dry cloth'],
        images: [{ url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?q=80&w=1000&auto=format&fit=crop', alt: 'Precision Kettlebell', isPrimary: true }],
        colors: [{ name: 'Matte Black (Yellow Band)', hex: '#1C1917' }],
        sizes: [{ size: '16 KG / 35 LBS', inStock: true, stockCount: 20 }],
        rating: 4.9,
        reviewCount: 52,
        isFeatured: true,
        badge: 'Solid Cast',
      },
    ],
  },
  {
    slug: 'demo-jewelry',
    name: 'Aurum Haute Jewels & Watches',
    category: 'jewelry',
    categoryLabel: '💎 Luxury Jewelry, Watches & Gems',
    tagline: 'Certified Solitaire Diamonds, 18K Solid Gold & Swiss Horological Watches',
    primaryColor: '#070C18',
    accentColor: '#EAB308',
    secondaryColor: '#0B1226',
    headingFont: 'Playfair Display',
    bodyFont: 'Plus Jakarta Sans',
    planId: 'plan_enterprise',
    planName: 'Enterprise SaaS Tier',
    ownerName: 'Alistair Montgomery',
    ownerEmail: 'jewelry-demo@mavenco.cloud',
    categories: [
      { id: 'cat_jwl_1', name: 'Diamond Rings', slug: 'rings', description: 'Solitaire engagement rings and emerald cut eternity bands', image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_jwl_2', name: 'Fine Necklaces', slug: 'necklaces', description: '18K solid yellow and white gold floating diamond pendants', image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_jwl_3', name: 'Luxury Timepieces', slug: 'watches', description: 'Swiss mechanical automatics with exhibition casebacks', image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_jwl_4', name: 'Baroque Pearls', slug: 'pearls', description: 'Handcrafted Australian South Sea and freshwater pearl chokers', image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop' },
    ],
    products: [
      {
        name: '18K Yellow Gold Floating Diamond Pendant',
        slug: '18k-gold-floating-diamond-pendant-demo-jewelry',
        sku: 'JWL-NCK-001',
        department: 'jewelry',
        category: 'necklaces',
        categoryName: 'Fine Necklaces',
        price: 28500,
        compareAtPrice: 38000,
        discountPercent: 25,
        shortDescription: '0.75 Carat VVS1 round brilliant certified lab diamond set in 18K solid yellow gold.',
        description: 'Minimalist illusion setting allows the diamond to float effortlessly along the collarbone. Includes a 45cm adjustable 18K solid gold curb chain.',
        features: ['0.75 ct VVS1 Clarity, E Color Certified Diamond', 'Hallmarked 18K (750) Solid Yellow Gold', 'Laser-inscribed IGI certificate included'],
        fabric: '18K Solid Gold & VVS1 Diamond',
        careInstructions: ['Clean gently with included jewelry polishing cloth'],
        images: [{ url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000&auto=format&fit=crop', alt: 'Diamond Pendant', isPrimary: true }],
        colors: [{ name: '18K Yellow Gold', hex: '#FFD700' }, { name: '18K White Gold', hex: '#E5E4E2' }],
        sizes: [{ size: '45cm Chain (0.75ct)', inStock: true, stockCount: 9 }],
        rating: 5.0,
        reviewCount: 47,
        isFeatured: true,
        isBestSeller: true,
        badge: 'Certified IGI',
      },
      {
        name: 'Baguette Solitaire Emerald Cut Eternity Band',
        slug: 'baguette-emerald-cut-eternity-band-demo-jewelry',
        sku: 'JWL-RNG-002',
        department: 'jewelry',
        category: 'rings',
        categoryName: 'Diamond Rings',
        price: 34999,
        compareAtPrice: 46000,
        discountPercent: 24,
        shortDescription: 'Continuous channel-set baguette diamonds (2.20 TCW) in 18K white gold.',
        description: 'A striking architectural statement ring. Each baguette diamond is hand-sorted for precision color and clarity matching across the entire band.',
        features: ['2.20 Total Carat Weight (TCW) VS+ diamonds', 'Comfort-fit contoured inner band'],
        fabric: '18K White Gold & Natural Diamonds',
        careInstructions: ['Store in included velvet presentation box'],
        images: [{ url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1000&auto=format&fit=crop', alt: 'Eternity Band', isPrimary: true }],
        colors: [{ name: '18K White Gold', hex: '#E5E4E2' }],
        sizes: [{ size: 'Size 6', inStock: true, stockCount: 4 }, { size: 'Size 7', inStock: true, stockCount: 6 }, { size: 'Size 8', inStock: true, stockCount: 3 }],
        rating: 5.0,
        reviewCount: 38,
        isFeatured: true,
        badge: 'Couture Piece',
      },
      {
        name: 'Swiss Automatic Sapphire Crystal Dress Watch',
        slug: 'swiss-automatic-sapphire-crystal-watch-demo-jewelry',
        sku: 'JWL-WAT-003',
        department: 'jewelry',
        category: 'watches',
        categoryName: 'Luxury Timepieces',
        price: 54000,
        compareAtPrice: 72000,
        discountPercent: 25,
        shortDescription: 'Calibre 2824-2 Swiss mechanical automatic movement with exhibition open caseback.',
        description: 'Classical dress watch perfection. Fluted 316L stainless steel case, sunburst guilloche dial, blued steel hands, and genuine alligator grain leather strap.',
        features: ['Swiss ETA 2824-2 Automatic Movement (28,800 vph)', 'Double-domed anti-reflective Sapphire Crystal', '50-Meter water resistance & 42h power reserve'],
        fabric: '316L Steel & Sapphire Glass',
        careInstructions: ['Service recommended every 4-5 years'],
        images: [{ url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1000&auto=format&fit=crop', alt: 'Swiss Watch', isPrimary: true }],
        colors: [{ name: 'Sunburst Silver & Black Strap', hex: '#C0C0C0' }],
        sizes: [{ size: '39mm Case', inStock: true, stockCount: 8 }],
        rating: 4.9,
        reviewCount: 31,
        isFeatured: true,
        badge: 'Swiss Made',
      },
      {
        name: 'Handcrafted Freshwater Baroque Pearl Choker',
        slug: 'freshwater-baroque-pearl-choker-demo-jewelry',
        sku: 'JWL-PRL-004',
        department: 'jewelry',
        category: 'pearls',
        categoryName: 'Baroque Pearls',
        price: 16800,
        compareAtPrice: 22000,
        discountPercent: 23,
        shortDescription: 'Lustrous AAA organic shape baroque pearls with an 18K solid gold toggle clasp.',
        description: 'Each organic pearl is uniquely shaped by nature, radiating a luminous iridescent luster. Strung on double-knotted pure silk thread.',
        features: ['12-14mm AAA Grade Organic Baroque Pearls', '18K Solid Gold heavy T-bar toggle clasp'],
        fabric: 'Freshwater Baroque Pearls & 18K Gold',
        careInstructions: ['Put on after applying perfume and makeup'],
        images: [{ url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop', alt: 'Baroque Pearl Choker', isPrimary: true }],
        colors: [{ name: 'Iridescent Pearl White', hex: '#FDFBF7' }],
        sizes: [{ size: '42cm Choker', inStock: true, stockCount: 11 }],
        rating: 4.8,
        reviewCount: 42,
        isFeatured: true,
        badge: 'Organic Luster',
      },
    ],
  },
  {
    slug: 'demo-grocery',
    name: 'FreshHarbor Organic Pantry',
    category: 'grocery',
    categoryLabel: '🌿 Gourmet Grocery & Organics',
    tagline: 'Single-Estate Specialty Coffee, Extra Virgin Cold-Pressed Oils & Organic Superfoods',
    primaryColor: '#09160E',
    accentColor: '#10B981',
    secondaryColor: '#F0FDF4',
    headingFont: 'Outfit',
    bodyFont: 'Plus Jakarta Sans',
    planId: 'plan_pro',
    planName: 'Professional Scale',
    ownerName: 'Julian Thorne',
    ownerEmail: 'grocery-demo@mavenco.cloud',
    categories: [
      { id: 'cat_gro_1', name: 'Specialty Coffee', slug: 'coffee', description: 'Single-origin roasted beans from high-altitude micro-lots', image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_gro_2', name: 'Cold-Pressed Oils', slug: 'pantry', description: 'Single-press extra virgin olive, avocado and walnut oils', image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_gro_3', name: 'Ceremonial Teas', slug: 'superfoods', description: 'Stoneground ceremonial Japanese Uji matcha and herbal infusions', image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_gro_4', name: 'Raw Forest Honey', slug: 'honey', description: 'Wild organic honey with raw comb harvested from deep forests', image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?q=80&w=1000&auto=format&fit=crop' },
    ],
    products: [
      {
        name: 'Ethiopian Yirgacheffe Single-Estate Whole Beans',
        slug: 'ethiopian-yirgacheffe-whole-beans-demo-grocery',
        sku: 'GRO-COF-001',
        department: 'grocery',
        category: 'coffee',
        categoryName: 'Specialty Coffee',
        price: 1299,
        compareAtPrice: 1699,
        discountPercent: 23,
        shortDescription: 'Washed process Arabica with delicate jasmine aroma, bergamot and peach notes.',
        description: 'Grown at 2,100m elevation in volcanic soils. Light-medium roast profile meticulously calibrated for pour-over, Chemex, and Aeropress brewing.',
        features: ['100% Specialty Grade Arabica (88 SCA score)', 'Direct-trade sustainably sourced from Gedeb micro-lot'],
        fabric: 'Degassing Valve Foil Bag (350g)',
        careInstructions: ['Store beans in airtight container at room temperature'],
        images: [{ url: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?q=80&w=1000&auto=format&fit=crop', alt: 'Coffee Beans Bag', isPrimary: true }],
        colors: [{ name: 'Whole Bean', hex: '#6F4E37' }],
        sizes: [{ size: '350g Bag', inStock: true, stockCount: 50 }],
        rating: 4.9,
        reviewCount: 88,
        isFeatured: true,
        isBestSeller: true,
        badge: '88 SCA Score',
      },
      {
        name: 'Cold-Pressed Extra Virgin Avocado Oil (500ml)',
        slug: 'cold-pressed-extra-virgin-avocado-oil-demo-grocery',
        sku: 'GRO-OIL-002',
        department: 'grocery',
        category: 'pantry',
        categoryName: 'Cold-Pressed Oils',
        price: 1850,
        compareAtPrice: 2400,
        discountPercent: 23,
        shortDescription: 'First cold-pressed Hass avocados with high 250°C smoke point and emerald hue.',
        description: 'Rich in heart-healthy monounsaturated fats and Vitamin E. Imparts a subtle buttery richness to gourmet salads, searing, and finishing drizzle.',
        features: ['Unrefined & unheated mechanical cold extraction', 'High smoke point of 250°C ideal for cooking'],
        fabric: 'UV-Protected Dark Glass Bottle (500ml)',
        careInstructions: ['Keep tightly sealed in cool pantry'],
        images: [{ url: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?q=80&w=1000&auto=format&fit=crop', alt: 'Avocado Oil Bottle', isPrimary: true }],
        colors: [{ name: 'Emerald Green', hex: '#50C878' }],
        sizes: [{ size: '500ml Bottle', inStock: true, stockCount: 30 }],
        rating: 4.8,
        reviewCount: 57,
        isFeatured: true,
        badge: 'First Press',
      },
      {
        name: 'Ceremonial Grade Uji Matcha Green Tea Powder',
        slug: 'ceremonial-grade-uji-matcha-powder-demo-grocery',
        sku: 'GRO-TEA-003',
        department: 'grocery',
        category: 'superfoods',
        categoryName: 'Ceremonial Teas',
        price: 2199,
        compareAtPrice: 2899,
        discountPercent: 24,
        shortDescription: 'First spring harvest stoneground tencha leaves from Uji, Kyoto with umami finish.',
        description: 'Vibrant electric green powder with zero bitterness. Packed with L-theanine and antioxidants for calm, focused morning energy.',
        features: ['First harvest spring-picked tencha leaves', 'Traditional granite stone mill grinding process'],
        fabric: 'Airtight Vacuum Sealed Tin (50g)',
        careInstructions: ['Refrigerate after opening for peak freshness'],
        images: [{ url: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?q=80&w=1000&auto=format&fit=crop', alt: 'Uji Matcha Tin', isPrimary: true }],
        colors: [{ name: 'Electric Matcha Green', hex: '#87A922' }],
        sizes: [{ size: '50g Tin', inStock: true, stockCount: 38 }],
        rating: 5.0,
        reviewCount: 96,
        isFeatured: true,
        badge: 'Kyoto Harvest',
      },
      {
        name: 'Raw Unfiltered Forest Wildflower Honey (1kg)',
        slug: 'raw-unfiltered-forest-wildflower-honey-demo-grocery',
        sku: 'GRO-HNY-004',
        department: 'grocery',
        category: 'honey',
        categoryName: 'Raw Forest Honey',
        price: 1450,
        compareAtPrice: 1950,
        discountPercent: 25,
        shortDescription: 'Pure raw comb honey collected from high-altitude Himalayan wildflower forests.',
        description: 'Never heated, pasteurized, or ultra-filtered. Contains live beneficial enzymes, wild bee pollen, and propolis in an amber glass jar.',
        features: ['100% Raw, Unpasteurized & Pure Comb', 'Rich in natural pollen and protective propolis'],
        fabric: 'Heavy Glass Jar with Honeycomb (1kg)',
        careInstructions: ['Do not refrigerate; crystallizes naturally'],
        images: [{ url: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?q=80&w=1000&auto=format&fit=crop', alt: 'Raw Forest Honey Jar', isPrimary: true }],
        colors: [{ name: 'Deep Amber Gold', hex: '#FFBF00' }],
        sizes: [{ size: '1 KG Jar', inStock: true, stockCount: 42 }],
        rating: 4.9,
        reviewCount: 71,
        isFeatured: true,
        badge: 'Raw & Wild',
      },
    ],
  },
  {
    slug: 'demo-footwear',
    name: 'KicksForge Sneaker Studio',
    category: 'footwear',
    categoryLabel: '👟 Footwear & Hype Sneakers',
    tagline: 'Limited Edition Retro High-Tops, Performance Runners & Handcrafted Leather Shoes',
    primaryColor: '#111827',
    accentColor: '#8B5CF6',
    secondaryColor: '#1F2937',
    headingFont: 'Outfit',
    bodyFont: 'Inter',
    planId: 'plan_pro',
    planName: 'Professional Scale',
    ownerName: 'Tariq Al-Mansoor',
    ownerEmail: 'footwear-demo@mavenco.cloud',
    categories: [
      { id: 'cat_ftw_1', name: 'Retro High-Tops', slug: 'high-tops', description: 'Iconic basketball silhouette streetwear high-top sneakers', image: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_ftw_2', name: 'Performance Runners', slug: 'runners', description: 'Ultra-cushioned responsive everyday running trainers', image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_ftw_3', name: 'Hand-Lasted Boots', slug: 'boots', description: 'Italian burnished calfskin Chelsea and lace-up boots', image: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_ftw_4', name: 'Minimalist Slip-Ons', slug: 'slip-ons', description: 'Vulcanized canvas skate shoes and suede slip-ons', image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?q=80&w=1000&auto=format&fit=crop' },
    ],
    products: [
      {
        name: 'Retro High Hypecourt Leather Sneakers',
        slug: 'retro-high-hypecourt-leather-sneakers-demo-footwear',
        sku: 'FTW-SNK-001',
        department: 'footwear',
        category: 'high-tops',
        categoryName: 'Retro High-Tops',
        price: 12999,
        compareAtPrice: 16999,
        discountPercent: 24,
        shortDescription: 'Premium full-grain tumbled leather high-top with vintage sail midsole cushioning.',
        description: 'Streetwear royalty. Features padded ankle collars for support, perforated toe box for breathability, and high-traction herringbone rubber outsoles.',
        features: ['Full-grain Italian tumbled leather upper', 'Air-pocket encapsulated heel cushioning'],
        fabric: 'Full-Grain Leather & Rubber Sole',
        careInstructions: ['Clean with specialist sneaker foam cleaner'],
        images: [{ url: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=1000&auto=format&fit=crop', alt: 'Retro High Sneakers', isPrimary: true }],
        colors: [{ name: 'Shadow Violet & White', hex: '#7C3AED' }, { name: 'Bred Black & Red', hex: '#DC2626' }],
        sizes: [{ size: 'UK 8', inStock: true, stockCount: 8 }, { size: 'UK 9', inStock: true, stockCount: 14 }, { size: 'UK 10', inStock: true, stockCount: 10 }],
        rating: 5.0,
        reviewCount: 142,
        isFeatured: true,
        isBestSeller: true,
        badge: 'Hype Drop',
      },
      {
        name: 'AeroFoam Cloud Ultra Lightweight Runners',
        slug: 'aerofoam-cloud-ultra-lightweight-runners-demo-footwear',
        sku: 'FTW-RUN-002',
        department: 'footwear',
        category: 'runners',
        categoryName: 'Performance Runners',
        price: 7499,
        compareAtPrice: 9999,
        discountPercent: 25,
        shortDescription: 'Sub-200g engineered knit runners with zero-gravity nitrogen foam rebound.',
        description: 'Feels like walking on clouds. Seamless one-piece knit upper breathes effortlessly while the flared heel counter cradles the Achilles tendon.',
        features: ['Weight: 198g (Size UK 9)', 'ZeroGravity dual-density rebound foam'],
        fabric: 'Engineered FlyKnit & Foam Outsole',
        careInstructions: ['Hand wash with mild detergent'],
        images: [{ url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000&auto=format&fit=crop', alt: 'Cloud Running Shoes', isPrimary: true }],
        colors: [{ name: 'Neon Purple', hex: '#8B5CF6' }, { name: 'Triple White', hex: '#F9FAFB' }],
        sizes: [{ size: 'UK 7', inStock: true, stockCount: 6 }, { size: 'UK 8', inStock: true, stockCount: 12 }, { size: 'UK 9', inStock: true, stockCount: 15 }],
        rating: 4.8,
        reviewCount: 83,
        isFeatured: true,
        badge: 'Sub-200g',
      },
      {
        name: 'Italian Burnished Leather Chelsea Boots',
        slug: 'italian-burnished-leather-chelsea-boots-demo-footwear',
        sku: 'FTW-BOT-003',
        department: 'footwear',
        category: 'boots',
        categoryName: 'Hand-Lasted Boots',
        price: 15800,
        compareAtPrice: 21000,
        discountPercent: 25,
        shortDescription: 'Goodyear welted Tuscan calfskin leather with elasticated side gussets and pull tabs.',
        description: 'The pinnacle of smart casual refinement. Hand-burnished by Italian artisans in Tuscany to develop a gorgeous bespoke patina over years of wear.',
        features: ['Goodyear-welted resoleable leather sole', 'Full leather lining with padded arch support'],
        fabric: 'Tuscan Full-Grain Calfskin',
        careInstructions: ['Treat with beeswax leather conditioner'],
        images: [{ url: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?q=80&w=1000&auto=format&fit=crop', alt: 'Leather Chelsea Boots', isPrimary: true }],
        colors: [{ name: 'Burnished Walnut Brown', hex: '#5D4037' }, { name: 'Onyx Black', hex: '#1C1917' }],
        sizes: [{ size: 'UK 8', inStock: true, stockCount: 5 }, { size: 'UK 9', inStock: true, stockCount: 9 }, { size: 'UK 10', inStock: true, stockCount: 6 }],
        rating: 4.9,
        reviewCount: 46,
        isFeatured: true,
        badge: 'Goodyear Welt',
      },
      {
        name: 'Vulcanized Canvas Skate Low-Tops',
        slug: 'vulcanized-canvas-skate-low-tops-demo-footwear',
        sku: 'FTW-SKT-004',
        department: 'footwear',
        category: 'slip-ons',
        categoryName: 'Minimalist Slip-Ons',
        price: 4499,
        compareAtPrice: 5999,
        discountPercent: 25,
        shortDescription: 'Heavy-duty 14oz organic cotton canvas with waffle gum rubber traction outsole.',
        description: 'Classic California low-profile skate shoe reinforced with double-stitched ollie zones and impact-absorbing polyurethane insoles.',
        features: ['14oz Heavy organic duck canvas', 'Vulcanized waffle gum rubber sole'],
        fabric: 'Organic Cotton Canvas & Gum Rubber',
        careInstructions: ['Spot clean with sneaker brush'],
        images: [{ url: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?q=80&w=1000&auto=format&fit=crop', alt: 'Canvas Low Tops', isPrimary: true }],
        colors: [{ name: 'Deep Black & White', hex: '#111827' }],
        sizes: [{ size: 'UK 8', inStock: true, stockCount: 15 }, { size: 'UK 9', inStock: true, stockCount: 20 }, { size: 'UK 10', inStock: true, stockCount: 12 }],
        rating: 4.7,
        reviewCount: 62,
        isFeatured: true,
        badge: 'Street Classic',
      },
    ],
  },
  {
    slug: 'demo',
    name: 'JQ Trends Universal Megastore',
    category: 'multipurpose',
    categoryLabel: '🛍️ Multi-Purpose Universal Megastore',
    tagline: 'The Multi-Purpose Flagship Destination for Fashion, Electronics & Modern Living',
    primaryColor: '#0F172A',
    accentColor: '#E11D48',
    secondaryColor: '#FFFFFF',
    headingFont: 'Playfair Display',
    bodyFont: 'Plus Jakarta Sans',
    planId: 'plan_enterprise',
    planName: 'Enterprise SaaS Tier',
    ownerName: 'Superadmin Platform',
    ownerEmail: 'demo@mavenco.cloud',
    categories: [
      { id: 'cat_multi_1', name: 'Fashion & Apparel', slug: 'fashion', description: 'Designer eveningwear, sarees, and tailoring', image: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_multi_2', name: 'Electronics & Audio', slug: 'electronics', description: 'Studio ANC audio and flagship smartwatches', image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_multi_3', name: 'Home & Living', slug: 'home', description: 'Scandinavian furniture and ceramic decor', image: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?q=80&w=1000&auto=format&fit=crop' },
      { id: 'cat_multi_4', name: 'Activewear & Gear', slug: 'fitness', description: 'Pro performance gym tights and carbon runners', image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=1000&auto=format&fit=crop' },
    ],
    products: [
      {
        name: 'Pure Mulberry Silk Banarasi Saree',
        slug: 'pure-mulberry-silk-banarasi-saree-demo',
        sku: 'JQT-FSH-001',
        department: 'women',
        category: 'fashion',
        categoryName: 'Fashion & Apparel',
        price: 14999,
        compareAtPrice: 19999,
        discountPercent: 25,
        shortDescription: 'Heirloom handwoven pure Katan silk saree with real gold zari kadwa motifs.',
        description: 'Certified pure mulberry silk Banarasi handloom masterpiece.',
        features: ['100% Pure Katan Silk', 'Gold Zari Kadwa weaving'],
        fabric: 'Pure Silk & Gold Zari',
        careInstructions: ['Dry clean only'],
        images: [{ url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1000&auto=format&fit=crop', alt: 'Banarasi Silk Saree', isPrimary: true }],
        colors: [{ name: 'Imperial Crimson', hex: '#8B0000' }],
        sizes: [{ size: 'Free Size', inStock: true, stockCount: 15 }],
        rating: 5.0,
        reviewCount: 48,
        isFeatured: true,
        badge: 'Heirloom Saree',
      },
      {
        name: 'Volt Pro Wireless ANC Studio Headphones',
        slug: 'volt-pro-wireless-anc-studio-headphones-demo',
        sku: 'JQT-AUD-002',
        department: 'electronics',
        category: 'electronics',
        categoryName: 'Electronics & Audio',
        price: 18999,
        compareAtPrice: 24999,
        discountPercent: 24,
        shortDescription: 'Hybrid Active Noise Cancellation with custom 45mm beryllium drivers and 65hr battery.',
        description: 'Studio grade audiophile wireless headphones with spatial sound.',
        features: ['45mm Beryllium Drivers', '-42dB Active Noise Cancelling'],
        fabric: 'Aluminium & Protein Leather',
        careInstructions: ['Store in included case'],
        images: [{ url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1000&auto=format&fit=crop', alt: 'Volt Headphones', isPrimary: true }],
        colors: [{ name: 'Space Gray', hex: '#2A2E39' }],
        sizes: [{ size: 'Over-Ear', inStock: true, stockCount: 20 }],
        rating: 4.9,
        reviewCount: 94,
        isFeatured: true,
        badge: 'Studio Audio',
      },
      {
        name: 'Handcrafted Fluted Ceramic Vase',
        slug: 'handcrafted-fluted-ceramic-vase-demo',
        sku: 'JQT-HOM-003',
        department: 'home',
        category: 'home',
        categoryName: 'Home & Living',
        price: 2499,
        compareAtPrice: 3499,
        discountPercent: 28,
        shortDescription: 'Minimalist Scandinavian ceramic vase with matte chalk glaze finish.',
        description: 'Sculptural fluted stoneware vase for modern living rooms.',
        features: ['Stoneware Clay', 'Matte Chalk Finish'],
        fabric: 'Matte Stoneware',
        careInstructions: ['Wipe clean with cloth'],
        images: [{ url: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?q=80&w=1000&auto=format&fit=crop', alt: 'Fluted Ceramic Vase', isPrimary: true }],
        colors: [{ name: 'Chalk White', hex: '#F5F5F3' }],
        sizes: [{ size: 'Medium (30cm)', inStock: true, stockCount: 22 }],
        rating: 4.9,
        reviewCount: 68,
        isFeatured: true,
        badge: 'Artisanal Decor',
      },
      {
        name: 'Retro High Hypecourt Leather Sneakers',
        slug: 'retro-high-hypecourt-leather-sneakers-demo',
        sku: 'JQT-FTW-004',
        department: 'footwear',
        category: 'fitness',
        categoryName: 'Activewear & Gear',
        price: 12999,
        compareAtPrice: 16999,
        discountPercent: 24,
        shortDescription: 'Premium full-grain tumbled leather high-top with vintage sail midsole cushioning.',
        description: 'Streetwear icon with encapsulated air cushioning.',
        features: ['Full-Grain Italian Tumbled Leather', 'Herringbone Rubber Outsole'],
        fabric: 'Leather & Rubber',
        careInstructions: ['Clean with sneaker foam'],
        images: [{ url: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=1000&auto=format&fit=crop', alt: 'Retro High Sneakers', isPrimary: true }],
        colors: [{ name: 'Black & Violet', hex: '#7C3AED' }],
        sizes: [{ size: 'UK 9', inStock: true, stockCount: 15 }],
        rating: 5.0,
        reviewCount: 142,
        isFeatured: true,
        badge: 'Hype Kicks',
      },
    ],
  },
];

async function seedCategoryDemos() {
  console.log('Connecting to MongoDB cluster...');
  const client = new MongoClient(uri);
  await client.connect();
  const platformDb = client.db('mavenco_platform');
  const now = new Date().toISOString();

  console.log(`Starting seeding for ${CATEGORY_DEMO_STORES.length} Category Demo Stores...`);

  for (const demo of CATEGORY_DEMO_STORES) {
    const cleanSlug = demo.slug;
    const tenantId = `store_${cleanSlug}`;
    const dedicatedDbName = `tenant_${cleanSlug}`;
    const tenantDb = client.db(dedicatedDbName);

    console.log(`\n======================================================`);
    console.log(`Setting up Category Demo Store: ${demo.name} (${cleanSlug})`);
    console.log(`Dedicated Database: ${dedicatedDbName}`);
    console.log(`======================================================`);

    const tenantRecord = {
      id: tenantId,
      name: demo.name,
      slug: cleanSlug,
      code: cleanSlug.substring(0, 4).toUpperCase(),
      category: demo.category,
      categoryLabel: demo.categoryLabel,
      isDemo: true,
      tagline: demo.tagline,
      status: 'active',
      planId: demo.planId,
      planName: demo.planName,
      databaseName: dedicatedDbName,
      currency: 'INR',
      ownerEmail: demo.ownerEmail,
      ownerName: demo.ownerName,
      primaryDomain: `${cleanSlug}.mavenco.cloud`,
      domains: [
        {
          id: `dom_${cleanSlug}`,
          domain: `${cleanSlug}.mavenco.cloud`,
          type: 'subdomain',
          isPrimary: true,
          status: 'connected',
          sslActive: true,
          createdAt: now,
        },
      ],
      theme: {
        logoUrl: '',
        primaryColor: demo.primaryColor,
        secondaryColor: demo.secondaryColor,
        accentColor: demo.accentColor,
        headingFont: demo.headingFont,
        bodyFont: demo.bodyFont,
        borderRadius: 'md',
      },
      metrics: {
        products: demo.products.length,
        orders: 142,
        customers: 86,
        monthlyRevenue: 245000,
        storageUsedMb: 45,
      },
      features: {
        customDomains: true,
        advancedAnalytics: true,
        richCms: true,
        productReviews: true,
        abandonedCart: true,
        aiFeatures: true,
        apiAccess: true,
      },
      updatedAt: now,
      createdAt: now,
    };

    // 1. Register in mavenco_platform.tenants & mavenco_platform.platform_tenants_registry
    await platformDb.collection('tenants').updateOne(
      { $or: [{ slug: cleanSlug }, { id: tenantId }] },
      { $set: tenantRecord },
      { upsert: true }
    );

    await platformDb.collection('platform_tenants_registry').updateOne(
      { $or: [{ slug: cleanSlug }, { id: tenantId }] },
      { $set: tenantRecord },
      { upsert: true }
    );

    // 2. Create / update admin user
    await platformDb.collection('users').updateOne(
      { email: demo.ownerEmail },
      {
        $set: {
          email: demo.ownerEmail,
          name: demo.ownerName,
          firstName: demo.ownerName.split(' ')[0],
          lastName: demo.ownerName.split(' ').slice(1).join(' ') || 'Admin',
          roleId: 'role_owner',
          role: 'owner',
          roleName: 'Store Owner & Administrator',
          tenantId: tenantId,
          tenantSlug: cleanSlug,
          password: `Mavenco@Demo2026!${cleanSlug}`,
          isTemporaryPassword: false,
          status: 'active',
          updatedAt: now,
        },
        $setOnInsert: {
          id: `user_${demo.ownerEmail.replace(/[^a-zA-Z0-9]/g, '_')}`,
          createdAt: now,
        },
      },
      { upsert: true }
    );

    // 3. Populate dedicated database (tenant_<slug>) with categories
    await tenantDb.collection('categories').deleteMany({});
    const categoryDocs = demo.categories.map((c, idx) => ({
      ...c,
      tenantSlug: cleanSlug,
      storeSlug: cleanSlug,
      displayOrder: idx + 1,
      createdAt: now,
      updatedAt: now,
    }));
    await tenantDb.collection('categories').insertMany(categoryDocs);
    console.log(`  -> Inserted ${categoryDocs.length} categories into ${dedicatedDbName}.categories`);

    // 4. Populate dedicated database with products
    await tenantDb.collection('products').deleteMany({});
    const productDocs = demo.products.map((p, idx) => ({
      ...p,
      id: `prod_${cleanSlug}_${idx + 1}`,
      tenantSlug: cleanSlug,
      storeSlug: cleanSlug,
      tenantId: tenantId,
      status: 'active',
      isPublished: true,
      inStock: true,
      stockCount: 50,
      createdAt: now,
      updatedAt: now,
    }));
    await tenantDb.collection('products').insertMany(productDocs);
    console.log(`  -> Inserted ${productDocs.length} products into ${dedicatedDbName}.products`);

    // Also mirror products in platformDb.products for legacy fallback queries
    await platformDb.collection('products').deleteMany({
      $or: [{ tenantSlug: cleanSlug }, { storeSlug: cleanSlug }, { tenantId: tenantId }],
    });
    await platformDb.collection('products').insertMany(productDocs);

    // 5. Populate homepage CMS page in dedicated database
    const cmsDoc = {
      tenantSlug: cleanSlug,
      type: 'homepage',
      status: 'published',
      sections: [
        {
          id: `hero_${cleanSlug}`,
          type: 'hero',
          name: 'Hero Lookbook Canvas',
          isActive: true,
          displayOrder: 1,
          content: {
            title: demo.name,
            subtitle: demo.tagline,
            badge: demo.categoryLabel,
            buttonText: 'Shop New Arrivals',
            buttonLink: `/stores/${cleanSlug}/new-arrivals`,
            secondaryButtonText: 'Explore Categories',
            secondaryButtonLink: `/stores/${cleanSlug}/categories`,
            backgroundImage: demo.products[0]?.images[0]?.url || '',
            themeMode: 'dark',
          },
        },
        {
          id: `categories_${cleanSlug}`,
          type: 'categories',
          name: 'Curated Categories',
          isActive: true,
          displayOrder: 2,
          content: {
            title: 'Shop By Department',
            subtitle: `Explore signature ${demo.name} collections`,
            categories: demo.categories.map((c) => ({
              id: c.id,
              name: c.name,
              slug: c.slug,
              image: c.image,
              link: `/stores/${cleanSlug}/${c.slug}`,
            })),
          },
        },
        {
          id: `trending_${cleanSlug}`,
          type: 'trending',
          name: 'Featured Masterpieces',
          isActive: true,
          displayOrder: 3,
          content: {
            title: 'Featured Collection',
            subtitle: `Hand-selected essentials from ${demo.name}`,
            limit: 4,
          },
        },
      ],
      updatedAt: now,
      createdAt: now,
    };

    await tenantDb.collection('cms_pages').updateOne(
      { tenantSlug: cleanSlug, type: 'homepage' },
      { $set: cmsDoc },
      { upsert: true }
    );
    await platformDb.collection('cms_pages').updateOne(
      { tenantSlug: cleanSlug, type: 'homepage' },
      { $set: cmsDoc },
      { upsert: true }
    );
    console.log(`  -> Configured homepage CMS sections for ${cleanSlug}`);
  }

  await client.close();
  console.log('\nAll 9 Category Demo Stores have been successfully seeded and verified in MongoDB!');
}

seedCategoryDemos().catch(console.error);
